### ISSUE TITLE
lyft policies won't play nice at ALL -- disable for now

### ISSUE THREAD

**Issue by lynnyliz** [weitzman/difficode#13]
Looks like the policy text for both lyft pages isn't actually rendered in the source code. Looking at the source, it seems like the actual text might be imported by a script. 

But here's the relevant code for the policy text if you Inspect Element:
```html
<div class="container terms-body ng-scope"> 
<section class="row m-x-s m-t-xl m-b-l p-t-l"> 
<article ng-bind-html="termsHtml" class="ng-binding">
<header class="masthead"></header>
<section>
    <article>
        <header>
            <h1> Lyft Terms of Service</h1>
```

I'm not sure how to make lyft's weird setup work with our diffi recipes. Any ideas? @weitzman

**Comment by weitzman** [comment]
I think we would have to change from request to a package that can execute
JavaScript. I think casperjs is an option. Let's disable lyft for now.

**Comment by weitzman** [comment]
The package we would need here is Phantomjs. Here is some info on running it at Heroku - http://mcranston18.github.io/phantom-js-on-heroku/. Not urgent.
