### ISSUE TITLE
uber -- bad privacy.hmtl; no terms

### ISSUE THREAD

**Issue by lynnyliz** [weitzman/difficode#15]
privacy.json has the right URL, but for some reason the imported HTML looks like a 403 page

**Comment by lynnyliz** [comment]
ISSUE PROGRESS:

- [x] add terms of service
- [ ] figure out what's going on with the privacy policy
- [ ] fix that

**Comment by lynnyliz** [comment]
`terms.html` and `terms.md` now exist in the uber dir, but `terms.selected.html` is still missing. This may be a selector issue. 

Adding the "markdown" label because the terms markdown page is just a heading

privacy policy still has the weird issue where we're feeding it the right URL but it seems like the wrong URL is being archived. Will look into on Heroku

**Comment by weitzman** [comment]
All I can gather is that Uber is blocking our app deliberately. Maybe it recognizes the Heroku IP range. They are very wary of bots gathering data. The recipe works when I run it from my laptop.

**Comment by lynnyliz** [comment]
What can we do about that (if anything)?

**Comment by weitzman** [comment]
This is now fixed. I've rewritten Diffi as a Python app and its much more reliable now.

See https://github.com/weitzman/diffi/issues for the current issue list.
