### ISSUE TITLE
bad markdown in facebook

### ISSUE THREAD

**Issue by lynnyliz** [weitzman/difficode#16]
redirects all pages to `facebook.com/unsupportedbrowser`

**Comment by weitzman** [comment]
Ugh. Like the Lyft recipes, this one might benefit from PhantomJS.

**Comment by lynnyliz** [comment]
How can we go about implementing that?

**Comment by lynnyliz** [comment]
Update: whoops, next time I'll go through my notification emails in
chronological order (didn't see your comment in the Lyft thread)
