### ISSUE TITLE
whitehouse -- awkward markdown; no terms 

### ISSUE THREAD

**Issue by lynnyliz** [weitzman/difficode#17]

**Comment by lynnyliz** [comment]
still not fixed (seems like recipes != application support)

**Comment by lynnyliz** [comment]
[This page] is the closest to a Terms of Service page that I could find on whitehouse.gov. I don't think it quite fits with the other legal documents we're collecting in diffi, so I'm downgrading this to only a markdown issue. There's not much else on this domain to make a recipe for.

**Comment by weitzman** [comment]
Looks good now.
