### ISSUE TITLE
only one file in verizon dir

### ISSUE THREAD

**Issue by lynnyliz** [weitzman/difficode#18]

**Comment by lynnyliz** [comment]
@weitzman Which Terms of Service do you want to use for Verizon? There's: 

1. [Terms of Use of their website](https://www.verizon.com/about/terms-conditions/terms-of-use)
2. [Terms of Use of verizonwireless.com](https://www.verizonwireless.com/b2c/globalText?textName=WEBSITE_USE&jspName=footer/webuse.jsp)
3. [Terms for Enterprise customers](http://www.verizonenterprise.com/terms/)
4. [Terms of Service for their phones](https://www.verizonwireless.com/b2c/globalText?textName=CUSTOMER_AGREEMENT&jspName=footer/customerAgreement.jsp)
5. [Terms of Service for their home internet](https://www.verizon.com/about/terms-conditions/residential-terms-service)
6. [a bunch of different Terms for various Business services](https://www.verizon.com/about/terms-conditions/business-terms-of-service)

I'm thinking number 1?

**Comment by lynnyliz** [comment]
Or a number of them, of course

**Comment by weitzman** [comment]
Gosh they must have a thousand lawyers there :)

Yeah, 1. is most urgent. Later on I'd be interested in 2,4,5. The recipe files should be named in order to indicate what the policy covers.

**Comment by lynnyliz** [comment]
Got it. I'll add the recipe for number 1, and edit the top post to include
a checklist of future policies to add.

**Comment by weitzman** [comment]
I added 1,4. Should be good enough for a while.
