### ISSUE TITLE
Only 1 file in google dir

### ISSUE THREAD

**Issue by weitzman** [weitzman/difficode#6]

**Comment by lynnyliz** [comment]
@weitzman We may want to reopen this issue -- looks like there's still no terms page in the google dir for some reason

**Comment by weitzman** [comment]
Reopened. I'll give you access to the logs soon.

**Comment by lynnyliz** [comment]
The original problem that this issue was opened for -- that is, a lack of terms page -- has now been fixed (woot! :tada:), however there are still missing files (those being `privacy.md` and `privacy.selected.html`). I'll open a new issue to address *those* missing files.
