### ISSUE TITLE
Bad files in xfinity

### ISSUE THREAD

**Issue by weitzman** [weitzman/difficode#8]

**Comment by lynnyliz** [comment]
Apparently going to `.../privacy` redirects to `.../privacy/2016-04`, at the moment. If xfinity keeps changing the URL of their policy page, is there some way we could still make it work?

Unfortunately, `.../terms` is more of a start page where you have to click specific links for specific services. Clicking on the Web Services TOS link takes you to another URL that has the date in it. Even if we could make the privacy policy work, I doubt we can do that for the terms.

**Comment by lynnyliz** [comment]
Option 2: We have Diffi watch the archive page (for terms: http://my.xfinity.com/terms/web/archive/), which will at least detect that the policy has been updated and provide the link to the new one. We miss out on the best part of this setup, which is the ability to see the differences parsed, but still get half the benefit, which is knowing that a service updates its terms even if they haven't told you.
